name: todo
services:
  main-db:
    image: postgres:18.3-alpine
    container_name: main-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pg-admin:
    image: dpage/pgadmin4
    container_name: pg-admin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - main-db
  
  tokens-cache:
    image: redis:7
    container_name: tokens-cache
    ports:
      - '6379:6379'
    volumes:
      - tokens-cache-data:/data
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin-data:
  tokens-cache-data: